version: '3'

services:
  your_application:
    build: .
    ports:
      - "8080:8080"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
